# Generated by Django 5.0 on 2023-12-15 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('Member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('dateOfMembership', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='members.member')),
                ('author_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
            ],
            bases=('members.member',),
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='members.member')),
                ('Reader_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
            ],
            bases=('members.member',),
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='members.member')),
                ('publishing_house_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.address')),
            ],
            bases=('members.member',),
        ),
    ]
