# Generated by Django 5.0 on 2023-12-21 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('author_birth_date', models.DateField()),
                ('author_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('Reader_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reader_birth_date', models.DateField()),
                ('reader_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('publishing_house_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.address')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('publishinghouse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='members.publishinghouse')),
                ('author_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='members.author')),
                ('reader_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='members.reader')),
                ('Member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=55)),
                ('dateOfMembership', models.DateTimeField(auto_now_add=True)),
                ('identity', models.CharField(choices=[('reader', 'Reader'), ('author', 'Author'), ('publishingHouse', 'PublishingHouse')], max_length=255)),
            ],
            bases=('members.reader', 'members.author', 'members.publishinghouse'),
        ),
    ]
